import {
	atOutline,
	barbellOutline,
	beerOutline,
	chatboxEllipsesOutline,
	extensionPuzzle,
	footstepsOutline,
	heartHalfOutline,
	logoNoSmoking,
	manOutline,
	medkitOutline,
	moonOutline,
	pizzaOutline,
	schoolOutline,
	sunnyOutline,
} from "ionicons/icons";

export const Basics = [
	{
		icon: moonOutline,
		type: "zodiacSign",
		question: "What is your zodiac sign?",
		data: [
			"Capricorn",
			"Aquarius",
			"Pisces",
			"Aries",
			"Taurus",
			"Gemini",
			"Cancer",
			"Leo",
			"Virgo",
			"Libra",
			"Scorpio",
			"Sagittarius",
		],
	},
	{
		icon: schoolOutline,
		type: "educationLevel",
		question: "What is your education level?",
		data: ["Bachelors", "In College", "High School", "PhD", "In Grad School", "Masters", "Trade School"],
	},
	{
		icon: manOutline,
		type: "childrens",
		question: "Do you want children?",
		data: [
			"I want children",
			"I don't want children",
			"I have children and want more",
			"I have children and don't want more",
			"Not sure yet",
		],
	},
	{
		icon: medkitOutline,
		type: "vaccinated",
		question: "Are you vaccinated?",
		data: ["Vaccinated", "Unvaccinated", "Prefer not to say"],
	},
	{
		icon: extensionPuzzle,
		type: "personalityType",
		question: "What’s your Personality Type?",
		data: [
			"INTJ",
			"INTP",
			"ENTJ",
			"ENTP",
			"INFJ",
			"INFP",
			"ENFJ",
			"ENFP",
			"ISTJ",
			"ISFJ",
			"ESTJ",
			"ISTP",
			"ISFP",
			"ESTP",
			"ESFP",
		],
	},
	{
		icon: chatboxEllipsesOutline,
		type: "communicationStyle",
		question: "What is your communication style?",
		data: [
			"I stay on WhatsApp all day",
			"Big time texter",
			"Phone caller",
			"Video chatter",
			"I'm slow to answer on WhatsApp",
			"Bad texter",
			"Better in person",
		],
	},
	{
		icon: heartHalfOutline,
		type: "receiveLove",
		question: "How do you receive love?",
		data: ["Thoughtful gestures", "Presents", "Touch", "Compliments", "Time together"],
	},
];

export const LifeStyle = [
	{
		icon: footstepsOutline,
		type: "pets",
		question: "Do you have any pets?",
		data: [
			"Dog",
			"Cat",
			"Reptile",
			"Amphibian",
			"Bird",
			"Fish",
			"Don't have but love",
			"Other",
			"Turtle",
			"Hamster",
			"Rabbit",
			"Pet-free",
			"All the pets",
			"Want a pet",
			"Allergic to pets",
		],
	},
	{
		icon: beerOutline,
		type: "drinking",
		question: "How often do you drink?",
		data: ["Not for me", "Sober", "Sober curious", "On special occasions", "Socially on weekends", "Most Nights"],
	},
	{
		icon: logoNoSmoking,
		type: "smoking",
		question: "How often do you smoke?",
		data: ["Social smoker", "Smoker when drinking", "Non-smoker", "Smoker", "Trying to quit"],
	},
	{
		icon: barbellOutline,
		type: "workout",
		question: "Do you workout?",
		data: ["Everyday", "Often", "Sometimes", "Never"],
	},
	{
		icon: pizzaOutline,
		type: "dietaryPreference",
		question: "What are your dietary preferences?",
		data: ["Vegan", "Vegetarian", "Pescatarian", "Kosher", "Halal", "Carnivore", "Omnivore", "Other"],
	},
	{
		icon: atOutline,
		type: "socialMedia",
		question: "How active are you on social media?",
		data: ["Influencer status", "Socially active", "Off the grid", "Passive scroller"],
	},
	{
		icon: sunnyOutline,
		type: "sleepingHabits",
		question: "What are your sleeping habits?",
		data: ["Early bird", "Night owl", "In a spectrum"],
	},
];
